name: 构建 arm android-19

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    
    - name: 拉取仓库
      uses: actions/checkout@v4
    - name: 安装MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: 安装py依赖
      run: pip install chardet
    - name: 构建 RainLanguageSO
      run: msbuild RainLanguageSO\RainLanguageSO.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64
    - name: 上传.so文件
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: libRainLanguageSO.so
        path: RainLanguageSO\ARM\Release\libRainLanguageSO.so
        retention-days: 1
        if-no-files-found: error


